Fix Styling
LethalCompanyCommunity/LethalAPI.Lobby pull request #4
Opened 2023-11-30 07:24 UTC by Redforce04

2023-11-30 14:20 UTC, MaxWasUnavailable requested changes
Got some feedback

2023-11-30 14:20 UTC, MaxWasUnavailable commented on LICENSE.txt
> +               GNU Lesser General Public License
LICENSE.txt shouldn't be a .txt file (we don't do this in Core either)

2023-11-30 14:20 UTC, MaxWasUnavailable commented on LethalAPI.Lobby/Plugin.cs
> +﻿// -----------------------------------------------------------------------
I'd prefer attribute-based, personally. Any reason We'd do interface-based?

2023-11-30 14:20 UTC, MaxWasUnavailable commented on LethalAPI.Lobby/Plugin.cs
> +        Log.Info($"Started plugin &3LethalAPI.Lobby &gv1.0.0 &rby &7LethalAPI Modding Community&r.{(this.Config.Debug ? " [&2Debug&r]" : string.Empty)}");
We should use the Plugin's variables for this, rather than hardcoding it.

I'd actually advise we have some kind of `AnnounceEnabled()` method in the base Plugin class that plugins can use tbh?

2023-11-30 16:04 UTC, Redforce04 commented on LICENSE.txt
> +               GNU Lesser General Public License
Resolved in discord

2023-11-30 16:05 UTC, Redforce04 commented on LethalAPI.Lobby/Plugin.cs
> +﻿// -----------------------------------------------------------------------
I think it's better to inherit the plug-in class for functionality.

2023-11-30 16:11 UTC, Redforce04 commented on LethalAPI.Lobby/Plugin.cs
> +﻿// -----------------------------------------------------------------------
If we add a feature such as translations or saving, it remains compiler safe. It also will show us if we are missing necessary features.

2023-11-30 16:12 UTC, Redforce04 commented on LethalAPI.Lobby/Plugin.cs
> +        Log.Info($"Started plugin &3LethalAPI.Lobby &gv1.0.0 &rby &7LethalAPI Modding Community&r.{(this.Config.Debug ? " [&2Debug&r]" : string.Empty)}");
Good idea. I copied this part from an attribute one but I agree this is smarter

2023-11-30 16:15 UTC, MaxWasUnavailable commented on LethalAPI.Lobby/Plugin.cs
> +﻿// -----------------------------------------------------------------------
Good point.

2023-11-30 20:00 UTC, Redforce04 commented on LethalAPI.Lobby/Plugin.cs
> +        Log.Info($"Started plugin &3LethalAPI.Lobby &gv1.0.0 &rby &7LethalAPI Modding Community&r.{(this.Config.Debug ? " [&2Debug&r]" : string.Empty)}");
> I'd actually advise we have some kind of `AnnounceEnabled()` method in the base Plugin class that plugins can use tbh?

By default the core should announce plugins. The real advantage of having this line is for when we add more stuff to the enabled method. If an exception is thrown, the plugin might not initialize properly, which may not manifest / announce the error.

 By adding this to the very end, we know the plugin has actually run through all of the necessary steps to initialize. If it is not present at all, there is a critical error somewhere along the way.
 
 Ultimately I am fine for outright deleting it and replacing it with a debug log, which won't be shown unless debug mode is on. This gets the best of both worlds.

2023-11-30 20:00 UTC, Redforce04 commented on LethalAPI.Lobby/Plugin.cs
> +        Log.Info($"Started plugin &3LethalAPI.Lobby &gv1.0.0 &rby &7LethalAPI Modding Community&r.{(this.Config.Debug ? " [&2Debug&r]" : string.Empty)}");
Also I keep it in the template for modders to use as a basic template.

2023-11-30 20:44 UTC, Redforce04 reviewed
Reviewed and adjusted.

2023-12-02 04:08 UTC, Redforce04 reviewed
Bumping this.

2023-12-06 18:02 UTC, MaxWasUnavailable approved these changes

2023-12-06 18:02 UTC, merged